[package]
name = "rolecop"
version = "0.1.0"
authors = ["Gina Maini <ginaandthecats@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# https://github.com/serenity-rs/serenity
serenity = "0.10"
